# polish first names
FIRST_NAMES = [
    "Jakub",
    "Zuzanna",
    "Kacper",
    "Julia",
    "Michał",
    "Zofia",
    "Szymon",
    "Maja",
    "Filip",
    "Hanna",
    "Aleksander",
    "Wiktoria",
    "Antoni",
    "Natalia",
    "Jan",
    "Emilia",
    "Wojciech",
    "Lena",
    "Mateusz",
    "Oliwia",
    "Piotr",
    "Amelia",
    "Kamil",
    "Martyna",
    "Tomasz",
    "Karolina",
    "Adam",
    "Klaudia",
    "Paweł",
    "Alicja",
    "Rafał",
    "Weronika",
    "Marek",
    "Magdalena",
    "Grzegorz",
    "Ewa",
    "Marcin",
    "Agata",
    "Łukasz",
    "Anna",
    "Dawid",
    "Katarzyna",
    "Bartosz",
    "Joanna",
    "Sebastian",
    "Gabriela",
    "Dominik",
    "Patrycja",
    "Artur",
    "Monika",
    "Michał",
    "Justyna",
    "Krzysztof",
    "Barbara",
    "Sławomir",
    "Elżbieta",
]

# polish last names
LAST_NAMES = [
    "Nowak",
    "Kowalski",
    "Wiśniewski",
    "Wójcik",
    "Kowalczyk",
    "Kamiński",
    "Lewandowski",
    "Zieliński",
    "Szymański",
    "Woźniak",
    "Dąbrowski",
    "Kozłowski",
    "Jankowski",
    "Witkowski",
    "Mazur",
    "Krawczyk",
    "Piotrowski",
    "Grabowski",
    "Zając",
    "Pawlak",
    "Michalski",
    "Król",
    "Wieczorek",
    "Jasiński",
    "Olszewski",
    "Baran",
    "Sikora",
    "Walczak",
    "Kubiak",
    "Wysocki",
    "Czarnecki",
    "Kucharski",
    "Sadowski",
    "Wojciechowski",
    "Bąk",
    "Kaczmarek",
    "Pietrzak",
    "Nowicki",
    "Szulc",
    "Wasilewski",
    "Kalinowski",
    "Ciesielski",
    "Klimczak",
    "Wojtasik",
    "Zalewski",
    "Kowalewski",
    "Szczepaniak",
    "Błaszczyk",
    "Kowal",
    "Górski",
    "Jabłoński",
    "Kozak",
    "Sienkiewicz",
    "Wysocka",
    "Krawczyk",
]

USER_REVIEWS = [
    (4.5, "Great quality and fast delivery!"),
    (4.0, "Good product, but the size was a bit off."),
    (5.0, "Absolutely love it! Will buy again."),
    (3.5, "Decent item, but expected better quality."),
    (4.5, "Exceeded my expectations! Highly recommend."),
    (2.0, "Not what I expected, quite disappointed."),
    (4.0, "Nice design and comfortable to wear."),
    (3.0, "Average quality, nothing special."),
    (5.0, "Perfect fit and great value for money!"),
    (4.0, "Good product, but delivery took longer than expected."),
    (3.5, "Okay quality, but the color was different from the picture."),
    (4.5, "Very satisfied with my purchase!"),
    (2.5, "Not worth the price, quality could be better."),
    (4.0, "Stylish and comfortable, would recommend."),
    (3.0, "It's okay, but I've seen better."),
    (5.0, "Fantastic item! Will definitely buy again."),
    (4.5, "Great value for money and fast shipping!"),
    (3.5, "Good quality, but the fit was a bit tight."),
    (4.0, "Really happy with this purchase!"),
    (2.0, "Disappointed with the quality, won't buy again."),
    (4.5, "Loved the design and the comfort!"),
    (3.0, "It's fine, but I expected more."),
    (5.0, "Best purchase I've made in a while!"),
    (4.0, "Good quality, but the delivery was slow."),
    (3.5, "Nice item, but not as described."),
    (4.5, "Very happy with my order!"),
    (2.5, "Quality is not great for the price."),
    (4.0, "Stylish and comfortable, would buy again."),
    (3.0, "It's okay, but I've seen better options."),
    (5.0, "Absolutely love it! Perfect fit and quality."),
    (4.5, "Great product, fast delivery, very satisfied!"),
    (3.5, "Decent quality, but the color was off."),
    (4.0, "Good item, but expected better quality."),
    (2.0, "Not worth the price, quite disappointed."),
    (4.5, "Exceeded my expectations! Highly recommend."),
    (3.0, "Average quality, nothing special."),
    (5.0, "Perfect fit and great value for money!"),
    (4.0, "Nice design and comfortable to wear."),
]
