# polish first names
FIRST_NAMES = sorted(
    set(
        [
            "Jakub",
            "Zuzanna",
            "Kacper",
            "Julia",
            "Michał",
            "Zofia",
            "Szymon",
            "Maja",
            "Filip",
            "Hanna",
            "Aleksander",
            "Wiktoria",
            "Antoni",
            "Natalia",
            "Jan",
            "Emilia",
            "Wojciech",
            "Lena",
            "Mateusz",
            "Oliwia",
            "Piotr",
            "Amelia",
            "Kamil",
            "Martyna",
            "Tomasz",
            "Karolina",
            "Adam",
            "Klaudia",
            "Paweł",
            "Alicja",
            "Rafał",
            "Weronika",
            "Marek",
            "Magdalena",
            "Grzegorz",
            "Ewa",
            "Marcin",
            "Agata",
            "Łukasz",
            "Anna",
            "Dawid",
            "Katarzyna",
            "Bartosz",
            "Joanna",
            "Sebastian",
            "Gabriela",
            "Dominik",
            "Patrycja",
            "Artur",
            "Monika",
            "Michał",
            "Justyna",
            "Krzysztof",
            "Barbara",
            "Sławomir",
            "Elżbieta",
        ]
    )
)
# polish last names
LAST_NAMES = sorted(
    set(
        [
            "Nowak",
            "Kowalski",
            "Wiśniewski",
            "Wójcik",
            "Kowalczyk",
            "Kamiński",
            "Lewandowski",
            "Zieliński",
            "Szymański",
            "Woźniak",
            "Dąbrowski",
            "Kozłowski",
            "Jankowski",
            "Witkowski",
            "Mazur",
            "Krawczyk",
            "Piotrowski",
            "Grabowski",
            "Zając",
            "Pawlak",
            "Michalski",
            "Król",
            "Wieczorek",
            "Jasiński",
            "Olszewski",
            "Baran",
            "Sikora",
            "Walczak",
            "Kubiak",
            "Wysocki",
            "Czarnecki",
            "Kucharski",
            "Sadowski",
            "Wojciechowski",
            "Bąk",
            "Kaczmarek",
            "Pietrzak",
            "Nowicki",
            "Szulc",
            "Wasilewski",
            "Kalinowski",
            "Ciesielski",
            "Klimczak",
            "Wojtasik",
            "Zalewski",
            "Kowalewski",
            "Szczepaniak",
            "Błaszczyk",
            "Kowal",
            "Górski",
            "Jabłoński",
            "Kozak",
            "Sienkiewicz",
            "Wysocka",
            "Krawczyk",
        ]
    )
)

# polish cities
CITIES = [
    "Warsaw",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Białystok",
    "Katowice",
    "Gdynia",
    "Częstochowa",
    "Radom",
    "Sosnowiec",
    "Toruń",
    "Kielce",
    "Gliwice",
    "Zabrze",
    "Olsztyn",
    "Bielsko-Biała",
    "Rzeszów",
    "Ruda Śląska",
    "Rybnik",
    "Dąbrowa Górnicza",
    "Elbląg",
    "Płock",
    "Opole",
    "Zielona Góra",
]

STREETS = [
    "Kwiatowa",
    "Słoneczna",
    "Leśna",
    "Polna",
    "Wiosenna",
    "Złota",
    "Srebrna",
    "Brązowa",
    "Różana",
    "Jasna",
    "Ciemna",
    "Węgierska",
    "Polska",
    "Francuska",
    "Hiszpańska",
    "Włoska",
    "Niemiecka",
    "Angielska",
    "Szwedzka",
    "Norweska",
    "Fińska",
    "Duńska",
    "Rosyjska",
    "Ukraińska",
    "Białoruska",
    "Czeska",
    "Słowacka",
    "Węgierska",
    "Rumuńska",
    "Bułgarska",
    "Serbska",
    "Chorwacka",
    "Słoweńska",
    "Grecka",
    "Turecka",
    "Cypryjska",
    "Portugalska",
    "Hiszpańska",
    "Włoska",
    "Francuska",
    "Belgijska",
    "Holenderska",
    "Szwajcarska",
    "Australijska",
    "Kanadyjska",
    "Amerykańska",
    "Argentyńska",
    "Brazylijska",
]

# shoes categories
CATEGORIES = ["Sneakers", "Boots", "Sandals", "Loafers", "Heels", "Flats", "Slippers"]
# shoes types
TYPES = ["Athletic", "Casual", "Formal", "Outdoor", "Work", "Fashion", "Comfort"]
# shoes styles
STYLES = ["Running", "Hiking", "Dress", "Casual", "Sport", "Work", "Fashion"]
# shoes brands
BRANDS = [
    "Aetheria Apparel",
    "Terra Nova Threads",
    "Vesper Collective",
    "Kinetic Stitch",
    "Obsidian Weave",
    "Luminary Loft",
    "Solstice Supply Co.",
    "Echo Garb",
    "Summit & Spoke",
    "Meridian Mode",
    "Wilde Folk Goods",
    "Cascade Clothiers",
    "Phantom Fit",
    "Nova Bloom",
    "Evergreen & Elm",
]
# shoes conditions
CONDITIONS = ["New", "Like New", "Very Good", "Good", "Fair", "Poor"]
# shoes materials
MATERIALS = ["Leather", "Canvas", "Synthetic", "Suede", "Mesh", "Rubber"]
# shoes colors
COLORS = [
    "Black",
    "White",
    "Brown",
    "Gray",
    "Navy",
    "Red",
    "Green",
    "Blue",
    "Yellow",
    "Pink",
    "Purple",
]
# shoes patterns
PATTERNS = [
    "Solid",
    "Striped",
    "Polka Dot",
    "Floral",
    "Geometric",
    "Graphic",
    "Plaid",
    "Camouflage",
]
# shoes widths
WIDTHS = ["Narrow", "Regular", "Wide", "Extra Wide"]
# shoes fasteners
FASTENERS = ["Laces", "Velcro", "Buckle", "Slip-On", "Zipper", "Elastic"]
# shoes heels
HEELS = ["Flat", "Low", "Medium", "High", "Wedge", "Platform"]
# shoes toes
TOES = ["Round", "Pointed", "Square", "Almond", "Open", "Closed"]


DESCRIPTIONS = [
    "A stylish and comfortable piece for everyday wear",
    "Perfect for casual outings or lounging at home",
    "Crafted with high-quality materials for durability",
    "A versatile item that can be dressed up or down",
    "Designed with a modern aesthetic in mind",
    "Ideal for layering or wearing on its own",
    "Features unique details that set it apart from the rest",
    "A must-have addition to any wardrobe",
    "Combines fashion and functionality seamlessly",
    "An essential piece for any fashion-forward individual",
    "Offers a perfect blend of comfort and style",
    "A timeless design that never goes out of fashion",
    "Made with sustainable practices in mind",
    "A statement piece that adds flair to any outfit",
    "Lightweight and breathable for all-day comfort",
    "Available in a range of sizes to fit every body type",
    "A classic design with a contemporary twist",
    "Perfect for transitioning between seasons",
    "A unique blend of colors and patterns for a standout look",
    "Crafted with attention to detail and quality craftsmanship",
    "A piece that tells a story with its design and materials",
    "An item that embodies the spirit of adventure and exploration",
    "A fusion of traditional and modern styles",
    "A piece that celebrates individuality and self-expression",
    "A versatile item that can be styled in multiple ways",
    "A piece that brings a touch of elegance to any outfit",
    "A comfortable and chic option for any occasion",
    "A piece that inspires confidence and creativity",
    "A timeless classic that will never go out of style",
    "A piece that reflects the latest fashion trends",
    "A unique item that stands out in any collection",
    "A piece that combines comfort and sophistication",
    "A versatile item that can be worn year-round",
    "A piece that adds a pop of color to any outfit",
    "A stylish option for both casual and formal occasions",
    "A piece that embodies the essence of modern fashion",
    "A unique blend of textures and materials for a standout look",
    "A piece that tells a story with its intricate design",
]
